### ISSUE TITLE
Do you have a more detailed tutorial on how to use it

### ISSUE THREAD

**Issue by Deepcong2019** [kage1020/Action-Segmentation-Utilities#1]

**Comment by kage1020** [comment]
Thank you for your comment.
This repository is still under development, so the tutorial is not well-organized yet. The usage might change with future updates, but here is a simple guide on how to use it:

1. Clone as a submodule

Clone this library as a submodule into the root of your project to make it easier to use:

```shell
git submodule add https://github.com/kage1020/Action-Segmentation-Utilities.git asu
```

This will create an asu folder in the root. You can also rename and place the cloned folder as needed.

2. Install poetry/dependencies

This repository uses [Poetry](https://python-poetry.org/), so it's recommended to install it. `pip` is also possible.

```shell
cd asu
poetry install
# or
pip install -r requirements.txt
```

3. Run code

After that, you can write code like the following to start training:

```python
from asu.base import Base, Config
from asu.manager import HydraManager
from asu.loader import BreakfastDataLoader
from asu.trainer import ASFormerTrainer, ASFormerCriterion, ASFormerOptimizer, ASFormerScheduler
from asu.models import ASFormer
from asu.evaluator import Evaluator

@HydraManager()
def main(cfg: Config):
    ctx = Base()
    dataloader = BreakfastDataLoader(cfg)
    model = ASFormer()
    model = Base.load_best_model(
        model, f"{cfg.base_dir}/{cfg.model_dir}", ctx.get_device(cfg.device)
    )
    criterion = ASFormerCriterion(
        num_classes=len(train_loader.str_to_int), mse_weight=0.15
    )
    optimizer = ASFormerOptimizer(model, lr=cfg.lr, weight_decay=cfg.weight_decay)
    scheduler = ASFormerScheduler(optimizer, mode="min", factor=0.5, patience=3)
    evaluator = Evaluator(backgrounds=cfg.backgrounds)
    trainer = ASFormerTrainer(
        cfg, model, criterion, optimizer, scheduler, evaluator
    )

    trainer.train(train_loader, test_loader)

if __name__ == "__main__":
    main()
```

---

Since it's not fully verified, please create an Issue or PR if you have any problems. We plan to update the documentation by August.

**Comment by kage1020** [comment]
I've added the README, so I close this issue for now. If you have any questions, feel free to leave a comment.
